In [1]:
import numpy as np
import pandas as pd

In [2]:
#!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00359/NewsAggregatorDataset.zip

In [3]:
#!unzip NewsAggregatorDataset.zip

In [4]:
#!rm -rf __MACOSX/

In [5]:
#ls

In [6]:
import pandas as pd
import tensorflow as tf
import re
import numpy as np
import os

In [7]:
column_names = ["TITLE", "URL", "PUBLISHER", "CATEGORY", "STORY", "HOSTNAME", "TIMESTAMP"]
news_dataset = pd.read_csv('newsCorpora.csv', names=column_names, header=None, delimiter='\t')
news_dataset.head()

TITLE  \
1  Fed official says weak data caused by weather,...   
2  Fed's Charles Plosser sees high bar for change...   
3  US open: Stocks fall after Fed official hints ...   
4  Fed risks falling 'behind the curve', Charles ...   
5  Fed's Plosser: Nasty Weather Has Curbed Job Gr...   

                                                 URL          PUBLISHER  \
1  http://www.latimes.com/business/money/la-fi-mo...  Los Angeles Times   
2  http://www.livemint.com/Politics/H2EvwJSK2VE6O...           Livemint   
3  http://www.ifamagazine.com/news/us-open-stocks...       IFA Magazine   
4  http://www.ifamagazine.com/news/fed-risks-fall...       IFA Magazine   
5  http://www.moneynews.com/Economy/federal-reser...          Moneynews   

  CATEGORY                          STORY             HOSTNAME      TIMESTAMP  
1        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM      www.latimes.com  1394470370698  
2        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM     www.livemint.com  1394470371207  
3        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM  www.ifamagazine.com  1394470371550  
4        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM  www.ifamagazine.com  1394470371793  
5        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM    www.moneynews.com  1394470372027

In [8]:
df=news_dataset[['TITLE',"CATEGORY"]]

Four categories: Business (b), Science & Technology (t), Entertainment (e) and Health & Medicine (m).

In [9]:
from collections import Counter
Counter(df['CATEGORY'])

Counter({'b': 115967, 'e': 152469, 'm': 45639, 't': 108344})

In [10]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
leMapped=le.fit_transform(df["CATEGORY"].values)
list(le.classes_)

['b', 'e', 'm', 't']

In [11]:
leMapped

array([0, 0, 0, ..., 2, 2, 2])

In [18]:
import pickle
from pickle import HIGHEST_PROTOCOL
with open("cuisine-labels.p3", "wb") as handle:
    pickle.dump(obj=leMapped,
               file=handle,
               protocol=HIGHEST_PROTOCOL)
with open("cuisine-labels.p2", "wb") as handle:
    pickle.dump(obj=leMapped,
               file=handle,
               protocol=2)

In [12]:
from keras.utils.np_utils import to_categorical

labels = to_categorical(leMapped)
labels.__class__.__name__

Using TensorFlow backend.


'ndarray'

In [13]:
from keras.utils.np_utils import to_categorical

docs = df["TITLE"].values

In [14]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(docs)
vocab_size = len(t.word_index) + 1
# integer encode the documents
encoded_docs = t.texts_to_sequences(docs)
print(vocab_size)
# pad documents to a max length of 4 words
max_length = 40
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(len(padded_docs))

75287
422419


In [12]:
docs[0]

'Fed official says weak data caused by weather, should not slow taper'

In [22]:
import json
import pickle
#pickle.dump(t, open( "ingredients-tokeniser.p2", "wb" ),protocol=2)
pickle.dump(t, open( "ingredients-tokeniser.p3", "wb" ),protocol=pickle.HIGHEST_PROTOCOL)
#json.dumps(t.__dict__)

In [15]:
#!wget http://nlp.stanford.edu/data/glove.6B.zip && unzip glove.6B.zip

In [16]:
#rm 2pageSessions.csv glove.6B.200d.txt glove.6B.50d.txt glove.6B.300d.txt glove.6B.zip

In [17]:
# load the whole embedding into memory
embeddings_index = dict()
f = open('glove.6B.100d.txt')
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

Loaded 400000 word vectors.


In [15]:
embeddings_index

{'biennials': array([-0.049107 ,  1.0836   , -0.96898  , -0.1956   ,  0.5042   ,
         0.20568  ,  0.11316  , -0.27911  ,  0.25616  , -0.23222  ,
        -0.011899 , -0.84183  , -0.0075647, -0.19212  , -0.64505  ,
         0.14264  , -0.0040923,  1.0564   ,  0.51505  , -0.30537  ,
        -0.18885  ,  0.22644  ,  0.18101  ,  0.74606  ,  0.8864   ,
         0.18044  , -0.067711 , -0.0088145, -0.45453  , -0.33256  ,
        -0.38935  , -0.60575  , -0.13333  ,  0.10477  ,  0.016106 ,
         0.7391   ,  0.55728  , -0.31496  , -0.72784  , -0.32057  ,
         0.36874  ,  0.59379  , -0.23812  , -0.17137  ,  0.16075  ,
         0.30295  ,  0.50082  , -0.47355  , -0.082908 ,  0.25314  ,
         0.2779   , -0.35703  , -0.27447  , -0.67199  , -0.072644 ,
         1.1955   ,  0.17128  , -0.015494 , -0.41772  ,  0.25037  ,
        -0.35641  ,  1.0195   , -0.41484  ,  0.36529  , -0.43866  ,
        -0.51965  , -0.18813  , -0.2575   ,  0.1916   , -0.16878  ,
         0.34902  ,  0.29505  , -0.

In [16]:
print(t.word_index)

{'fawn': 40353, 'demystifies': 72033, "cake'": 33241, "'cautious": 38090, "thermonuclear'": 60504, '5275436': 59560, 'sowell': 48457, "'transparency": 49613, 'woods': 13498, 'spiders': 4284, 'hanging': 6495, 'woody': 4298, 'localized': 44712, 'tasos': 22996, 'usd18bn': 64705, 'caner': 56373, 'gad': 35623, 'mathison': 47804, 'dachel': 36285, 'caw': 49395, '\xe2\x80\x9ciwatch\xe2\x80\x9d': 40998, 'scold': 25160, 'insertion': 54183, 'originality': 24722, "'rise'": 30589, "diplomat's": 46747, "bynes'": 26180, 'unnecessarily': 42451, "'antitrust": 73241, "'daddy": 66948, "products's": 50478, 'gozira': 62657, 'deliberation': 41103, 'light\xe2\x80\x9d': 51768, "techdirt's": 72096, 'wracked': 69891, "franklin's": 37405, "'unsafe": 15643, "milestone'": 49031, 'kaspersky': 62552, 'appropriation': 33652, 'seldom': 71659, "hangin'": 39426, "'misplaced'": 39033, 'broward': 27781, 'bringing': 2737, "kingdom'": 39519, 'eretail': 62527, "'royal'": 42129, 'revelers': 20160, 'wooded': 51389, 'reportedy'

In [18]:
# create a weight matrix for words in training docs
embedding_matrix = np.zeros((vocab_size, 100))
for word, i in t.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

In [14]:
#embedding_matrix.dump("ingredients-embedding-matrix.dat")
np.save(file="docs-embedding-matrix.dat",
        arr=embedding_matrix,
        allow_pickle=False)
print(embedding_matrix.shape)

(3065, 100)


In [19]:
padded_docs

array([[  215,   452,    25, ...,     0,     0,     0],
       [ 1934,  6727,  8804, ...,     0,     0,     0],
       [   13,   314,    61, ...,     0,     0,     0],
       ...,
       [  721,    93, 16349, ...,     0,     0,     0],
       [ 5463,   984,  9340, ...,     0,     0,     0],
       [ 5463,   984,  9340, ...,     0,     0,     0]], dtype=int32)

In [20]:
labels

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]], dtype=float32)

In [21]:
from keras.models import Sequential
from keras.layers import Dense, Flatten, Dropout
from keras.layers.convolutional import Conv1D, MaxPooling1D
from keras.layers.embeddings import Embedding
from keras.callbacks import ModelCheckpoint
from sklearn.model_selection import KFold

# fix random seed for reproducibility
seed = 42
np.random.seed(seed)

# define 10-fold cross validation test harness

saveBestModelWeights = ModelCheckpoint("news_model_weights.h5",
                                       monitor='val_acc',
                                       verbose=1, 
                                       save_best_only=True,
                                       save_weights_only=False,
                                       mode='auto',
                                       period=1)

In [22]:


    # define the model
model = Sequential()
model.add(Embedding(vocab_size, 100, 
                        weights=[embedding_matrix],
                        input_length=40, 
                        trainable=False, 
                        name="embed"))
model.add(Conv1D(filters=128, 
                     kernel_size=3, 
                     activation='relu',
                     name="conv_1"))
model.add(MaxPooling1D(pool_size=5,
                           name="maxpool_1"))
model.add(Flatten(name="flat_1"))
model.add(Dropout(0.3,
                     name="dropout_1"))
model.add(Dense(128, 
                    activation='relu',
                    name="dense_1"))
model.add(Dense(le.classes_.size,
                    activation='softmax',
                    name="out_1"))
    
    # compile the model
model.compile(optimizer='rmsprop',
                  loss='binary_crossentropy',
                  metrics=['acc'])
    

model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embed (Embedding)            (None, 40, 100)           7528700   
_________________________________________________________________
conv_1 (Conv1D)              (None, 38, 128)           38528     
_________________________________________________________________
maxpool_1 (MaxPooling1D)     (None, 7, 128)            0         
_________________________________________________________________
flat_1 (Flatten)             (None, 896)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 896)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               114816    
_________________________________________________________________
out_1 (Dense)                (None, 4)                 516       
Total para

In [ ]:
        
    # fit the model
model.fit(padded_docs,
              labels,
              batch_size=16,
              epochs=5, # no benefit from additional epochs
              verbose=1,
              callbacks=[saveBestModelWeights])
    
    scores = model.evaluate(padded_docs[test], labels[test], verbose=0)
    print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
    cvscores.append(scores[1] * 100)

print("%.2f%% (+/- %.2f%%)" % (np.mean(cvscores), np.std(cvscores)))

Some of these files will be needed in the object store to support scoring service

In [28]:
import ibm_boto3
from ibm_boto3.s3.transfer import S3Transfer
from ibm_botocore.client import Config

credentials = {
    'endpoint': 'https://s3-api.us-geo.objectstorage.service.networklayer.com',
    'api_key': 'qGeOVR8vELnV0WibBE20hZQa1s-8J29WDzTKz9KPYmOt',
    'service_id': 'iam-ServiceId-3b0647f0-0a0f-4e3a-8955-dbfe2c19030d',
    'iam_service_endpoint': 'https://iam.ng.bluemix.net/oidc/token',
    'bucket': 'unileverfoods3aeacf7383764d8d838f13fdd1ae2bad'}

def put_file_COS(credentials, local_file_name):  
    client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id=credentials['api_key'],
    ibm_service_instance_id=credentials['service_id'],
    ibm_auth_endpoint=credentials['iam_service_endpoint'],
    config=Config(signature_version='oauth'),
    endpoint_url=credentials['endpoint'])
    transfer = S3Transfer(client)
    transfer.upload_file(local_file_name, credentials['bucket'],local_file_name)


In [29]:
put_file_COS(credentials, "cuisine-model-weights.h5")
put_file_COS(credentials, "ingredients-embedding-matrix.dat")
put_file_COS(credentials, "ingredients-tokeniser.p2")
put_file_COS(credentials, "ingredients-tokeniser.p3")
put_file_COS(credentials, "cuisine-labels.p2")
put_file_COS(credentials, "cuisine-labels.p3")
